import teknikum from "/images/Teknikum.jpg";
import ec from "/images/ec.jpg";

export const EducationData = [
	{
		institution: "EC Yrkeshögskola",
		imgSrc: ec,
		logoAlt: "EC Yrkeshögskola logo",
		program: "Frontend Development",
		location: "Växjö",
		startDate: "mars 2023",
		endDate: "Pågående",
		graduation: "24 Jan 2025",
		courses: [
			{ name: "HTML och CSS", credits: 35 },
			{ name: "JavaScript 1", credits: 40 },
			{ name: "JavaScript 2", credits: 35 },
			{ name: "JavaScript 3", credits: 35 },
			{ name: "UX & UI", credits: 25 },
			{ name: "Backend-utveckling 1", credits: 30 },
			{ name: "Backend-utveckling 2", credits: 35 },
			{ name: "LIA 1 Frontendutveckling", credits: 60 },
			{ name: "Agila Projektmetoder 2", credits: 20 },
			{ name: "Examensarbete", credits: 20 },
			{ name: "LIA 1 Frontendutveckling", credits: 65 },
		],
	},
	{
		institution: "Teknikum",
		imgSrc: teknikum,
		logoAlt: "teknikum logo",
		program:
			"El- och energiprogrammet inriktning Dator- och kommunikationsteknik",
		location: "Växjö",
		startDate: "juni 2013",
		endDate: "juni 2016",
		courses: [
			{ name: "Nätverksteknologier", credits: 100 },
			{ name: "Nätverksadministration", credits: 100 },
			{
				name: "Administration av nätverks- och serverutrustning",
				credits: 100,
			},
			{ name: "Dator- och nätverksteknik", credits: 100 },
			{ name: "Datorsamordning och support", credits: 100 },
			{ name: "Engelska 5", credits: 100 },
			{ name: "Kommunikationsnät 1", credits: 100 },
			{ name: "Mekatronik 1", credits: 100 },
			{ name: "Nätverkssäkerhet", credits: 100 },
			{ name: "Datorteknik 1a", credits: 100 },
			{ name: "Elektronik och mikrodatorteknik", credits: 100 },
			{ name: "Elektromekanik", credits: 100 },
			{ name: "Energiteknik 1", credits: 100 },
			{ name: "Engelska 6", credits: 100 },
			{ name: "Gymnasiearbete", credits: 100 },
			{ name: "Historia 1a1", credits: 50 },
			{ name: "Matematik 1a", credits: 100 },
			{ name: "Naturkunskap 1a1", credits: 50 },
			{ name: "Nätverksteknik", credits: 100 },
			{ name: "Programmering 1", credits: 100 },
			{ name: "Religionskunskap 1", credits: 50 },
			{ name: "Samhällskunskap 1a1", credits: 50 },
			{ name: "Service och reparationsarbete", credits: 100 },
			{ name: "Svenska 1", credits: 100 },
			{ name: "Svenska 2", credits: 100 },
			{ name: "Idrott och hälsa 1", credits: 100 },
			{ name: "Svenska 3", credits: 100 },
		],
	},
];
